### PR TITLE
Run Discord RPC in a seperate thread

### PR DESCRIPTION
**Pull request by Dpeta**
Avoids the blocking socket operations freezing up the entire game.

The thread is daemonic so it'll just die if the main thread ends, it's only given one second to close properly on exit.

### CODE REVIEW

**Comment by Dpeta** [comment]
Will probably leave this a draft until there's a release branch & the discord setting pr is merged, I'll rebase if there's a conflict. Still gotta:
 - Remove debug prints
 - Check if there's a way to check if the thread is finished without defining an event for it.

**Comment by lillithrosepup** [comment]
Release branch is made and my prs are merged so you can make this not a draft now :D

**Comment by Dpeta** [comment]
Should be good now 🎉

**Comment by Dpeta** [comment]
\* :"3

**Pull request merged**
