### PR TITLE
Kit Trait Changes

### PR DESCRIPTION
**Pull request by keplerstelescope**
## About The Pull Request

moved around kit traits to make more sense with the equivalent range normal traits:
- daydreamer lines up with playful's sillier, more kit-like/wondering, but still stable nature; and barely seems to line up with strict at all
- charming does work with playful, but it lines up very well with charismatic since the two words are synonyms and the thoughts of both traits involve very similar ideas (other cats liking the charming/charismatic cat a lot)
- fearless is the kit trait that was named daring before kit traits were disambiguated from normal traits, and that shows in the related thoughts. fearless is synonyms with bold/daring, and the trait (and the thoughts related to it) lines up very well with them
- know-it-all is an okay match for ambitious, but it lines up with strict very well, particularly with thoughts involving correcting another cat on something trivial, telling another cat that they should know more about types of moss, having memorized the warrior code already, etc. know-it-all and strict share a "things need to be correct" vibe 
- bossy does somewhat align with confident, but it's not too hard to argue that it lines up with ambitious better, with thoughts about wanting to be deputy/leader, and a lot of telling other cats what to do. bossy and ambitious both are traits that want to be in charge
- noisy is perhaps the edit i was least sure about, but it does match pretty well with confident. noisy kits seem to be unabashed (particularly in the use of their voice), and confident can be seen as a more mature version of that, doing things like boasting about their ability to catch prey and feeling secure in the space they take up.

also made some edits to thoughts/alive/kitten.json, particularly merging the "daring" kit thoughts into "fearless" since "daring" is not in the kit traits dict of trait-ranges.json and "fearless" is what it was renamed to. all other changes in kitten.json are minor fixes (one typo, some small edits to sentence flow, adding random_living_status: living where r_c is mentioned)

## Why This Is Good For ClanGen

these changes make the development of a cat's personality as they grow from a kit to an apprentice more intuitive and natural. particularly with the daydreamer kit trait and the strict normal trait, it is now much less likely that a kit suddenly becomes significantly different in personality and behavior as they become an adolescent.

## Proof of Testing

trait - daydreamer to playful
trait - fearless to daring
trait - bossy to ambitious
trait - charming to charismatic

## Changelog/Credits

trait ranges adjusted for the following kit traits: daydreamer, charming, fearless, know-it-all, bossy, noisy
"daring" kit thoughts merged with "fearless" to go along with "daring" kit trait being renamed to "fearless" in the past disambiguation of kit traits and normal traits

### CODE REVIEW

**Comment by anjubatus** [comment]
Hi, I see this PR include typofixes and other adjustments that aren't related to kit trait changes. In the future, please have those in a separate PR that explains those changes instead of including them in the same PR of a different subject. Other than that, I agree with how you matched kit traits to adult traits!

**Comment by keplerstelescope** [comment]
oh i apologize! should i edit those changes out of this one? and if so, does that include a reversion of the removal of the daring kit thoughts? (i was considering that part, at least, to be related since the unavailability of the trait for kits is from trait-ranges.json too)

**Comment by scribblecrumb** [comment]
@keplerstelescope The daring changes can stay!

**Comment by keplerstelescope** [comment]
edited out the thoughts/alive/kitten.json changes that aren't directly related to the merge of the "daring" thoughts into "fearless"! i hope that means it's good to go :0

**Review by scribblecrumb — APPROVED** [review]

**Comment by scribblecrumb** [comment]
Great! Feel free to create a different PR with those changes :+1: 

Also, are you already part of the dev team on discord? I don't recognize your username but i may just be forgetting lol

**Comment by keplerstelescope** [comment]
> Also, are you already part of the dev team on discord? I don't recognize your username but i may just be forgetting lol

i am not! i am interested in potentially being a part of it tho! (i really like fixing spelling/grammar issues :p)

**Pull request merged**
