### PR TITLE
LUNA fixed unittests (hail Luna)

### PR DESCRIPTION
**Pull request by hobohime**
**EDIT**

Luna fixed the issue with the test saves not importing by including in test.yml code that downloads the two test saves as zips and unzips them, meaning that all tests can now run.

While Luna asked me to edit in the fix for her as she didn't want to include all of the comments she made, the issue was solved by Luna, and we should all bow to Luna supremacy.

### CODE REVIEW

**Comment by hobohime** [comment]
Another solution, which I do not know how to do, is create the submodule for test/test_save.py for it to check, but as of this version of dev, the submodule doesn't exist. It is a deletion of a check that checks for something that does not exist to my knowledge.

**Comment by lillithrosepup** [comment]
if anyone brings back the submodule yeet them into the abyss

**Comment by hobohime** [comment]
> if anyone brings back the submodule yeet them into the abyss

Wait so this submodule is NOT supposed to exist?

**Comment by lillithrosepup** [comment]
inorder to fix that wed have to bundle two extra test saves with the dev version whichd just be annoying. the reason [this](https://github.com/ImLvna/clangen-unittest-saves) was in a submodule was so testers didnt have to download it, but devs and the unittest runner could use them.

**Comment by lillithrosepup** [comment]
wait nvm im dumb n can patch it :3

**Comment by hobohime** [comment]
> wait nvm im dumb n can patch it :3

Okay! If you can patch it, your patch will be the one that should be included instead of mine!

Just let me know if you manage it and I can yeet this one

**Comment by lillithrosepup** [comment]
fuck i hate gh actions. i did way too many commits to make a pr bc itd clutter the history, can you change test.yml to this :cutie: https://github.com/ImLvna/clangen/blob/patch-1/.github/workflows/test.yml

**Comment by lillithrosepup** [comment]
image
violently crying rn

**Pull request merged**
