### PR TITLE
Closes #2576: Double Click Feature

### LINKED ISSUE #2576: [CODE] QoL: Double-click to quick add cats to a patrol
**Description**
Double-clicking a cat should add/remove them from the current patrol (depending on which box they're currently in). Not sure what else to say here lol, it's a little quality of life thing.

Related: #2208

### PR DESCRIPTION
**Pull request by Sumwatt0**
## About The Pull Request
This enables double clicking for cat buttons. When you double click the cat, it adds / removes it from the patrol. 

## Why This Is Good For ClanGen
This improves quality of life and allows players to make patrols quicker.

## Linked Issues
Closes #2576.

## Proof of Testing
https://github.com/user-attachments/assets/4bcad267-7b18-4bdd-a099-69b65a99d5db

## Changelog/Credits
[FEATURE]: Double click to add / remove cats from the patrol.

Credits (Sumwatt/Sumwatt0)

### CODE REVIEW

**Comment by archanyhm** [comment]
Wouldn't right-clicking be more intuitive for adding/removing from patrol? If I'm thinking of other games, I feel like right click is used more prevalently.

**Comment by j-gynn** [comment]
It makes sense to me that you double-click - once to "select" the cat, once to "quick-move". Then again, I'm the one who made the suggestion so *obviously* I'd agree with it lol

**Comment by DeadGirlRisen** [comment]
Personally, I try and double click on the patrol cats by accident all the time to add and remove them quickly. It wouldn't cross my mind to right click personally. But thats just my opinion on this.

**Comment by archanyhm** [comment]
> It makes sense to me that you double-click - once to "select" the cat, once to "quick-move". Then again, I'm the one who made the suggestion so _obviously_ I'd agree with it lol

I personally feel like double-clicking would be more akin to "open this" rather than "move this", but I think those semantics are flexible. The simplest example would be files in a folder on most operating systems. Maybe some more folks will chime in, otherwise you may write this off as Arch being silly again and merge this asap.

**Comment by Sumwatt0** [comment]
I don't mind which keybind it is so I made a poll in #dev-game-talk on the discord and a couple more people preferred double click to be the default (it was really close though). I'll make a key remapping system when this is merged so it can be changed to something else.

**Review by scribblecrumb — APPROVED** [review]

**Pull request merged**
