### PR TITLE
Dark Forest Ceremonies

### PR DESCRIPTION
**Pull request by Ronfaure**
The rest of the unclaimed Dark Forest Ceremonies

### CODE REVIEW

**Comment by thebitterstorm** [comment]
Noticed a few typos and thought I should point 'em out. I don't mean any of this in ill-will whatsoever.

`"text": "r_c began {PRONOUN/r_c/poss} prepared speech for {PRONOUN/r_c/poss} life, when m_c interrupted the **speil** to point out a word out of place. Disgruntled, r_c gives m_c a life for [virtue]."`
**Speil** should be spelt as **spiel**.

`"text": "r_c snarls as the live of [virtue] is given, winding around m_c's body like a snake. All of the new leader's plans and thoughts will crumble to dust unless {PRONOUN/m_c/subject} {VERB/m_c/acts/act} **qucikly**, rashly!"`
**Qucikly** should be spelt as **quickly** and you should consider adding **and** between quickly and rashly. It flows better in my opinion.

`text": "r_c whispered sweetly for m_c to deafen {PRONOUN/m_c/self} from the cowardly, cautious cries of {PRONOUN/m_c/poss} Clan as the dark spirit gives a life for **]virtue]**."`
**]virtue]** should be [virtue].

`"text": "r_c presses {PRONOUN/r_c/poss} nose against m_c's forehead, the virtue of [virtue] burning away the leader's previous life. Loyalty to {PRONOUN/r_c/poss} Clan must be absolute, and no weakness must be tolerated."`
I think, "no weakness must be tolerated," sounds a bit odd for the context. It might be better rephrased as: "no weakness can be tolerated."

`"text": "Appearing behind m_c from the murk, a dark tail passed in front of m_c's eyes. The **shadopws** distorted the life giver's voice, but {PRONOUN/m_c/subject} swore {PRONOUN/m_c/subject} could hear r_c teasing {PRONOUN/r_c/object}. The life of [virtue] ebbed away before m_c could see if it was really {PRONOUN/r_c/object}."`
**shadopws** should be shadows.

**Comment by Ronfaure** [comment]
> Noticed a few typos and thought I should point 'em out. I don't mean any of this in ill-will whatsoever.
> 
> `"text": "r_c began {PRONOUN/r_c/poss} prepared speech for {PRONOUN/r_c/poss} life, when m_c interrupted the **speil** to point out a word out of place. Disgruntled, r_c gives m_c a life for [virtue]."` **Speil** should be spelt as **spiel**.
> 
> `"text": "r_c snarls as the live of [virtue] is given, winding around m_c's body like a snake. All of the new leader's plans and thoughts will crumble to dust unless {PRONOUN/m_c/subject} {VERB/m_c/acts/act} **qucikly**, rashly!"` **Qucikly** should be spelt as **quickly** and you should consider adding **and** between quickly and rashly. It flows better in my opinion.
> 
> `text": "r_c whispered sweetly for m_c to deafen {PRONOUN/m_c/self} from the cowardly, cautious cries of {PRONOUN/m_c/poss} Clan as the dark spirit gives a life for **]virtue]**."` **]virtue]** should be [virtue].
> 
> `"text": "r_c presses {PRONOUN/r_c/poss} nose against m_c's forehead, the virtue of [virtue] burning away the leader's previous life. Loyalty to {PRONOUN/r_c/poss} Clan must be absolute, and no weakness must be tolerated."` I think, "no weakness must be tolerated," sounds a bit odd for the context. It might be better rephrased as: "no weakness can be tolerated."
> 
> `"text": "Appearing behind m_c from the murk, a dark tail passed in front of m_c's eyes. The **shadopws** distorted the life giver's voice, but {PRONOUN/m_c/subject} swore {PRONOUN/m_c/subject} could hear r_c teasing {PRONOUN/r_c/object}. The life of [virtue] ebbed away before m_c could see if it was really {PRONOUN/r_c/object}."` **shadopws** should be shadows.

Thank you for the keen eye! Fixed them up

**Comment by thebitterstorm** [comment]
`"text": "Puffing out {PRONOUN/r_c/poss} chest, r_c gives m_c a life for [virtue] and dares {PRONOUN/m_c/object} to make c_n an even better Clan than anyone ever could!"`
I'm pretty sure that after {PRONOUN/r_c/poss}, there are two spaces instead of one. You might want to go check that.

`"text": "Such a theatric attitude had no place in the Dark Forest. But the gloom-covered spirit of r_c gives m_c a life for [virtue] with silent contempt in {PRONOUN/r_c/poss} eyes regardless of {PRONOUN/r_c/poss} feelings on the matter."`
Same thing as above. I could be wrong, but might be worth a quick check.

`"text": "So long as m_c uses {PRONOUN/m_c/poss} rebellious ways to destroy the hold StarClan has on the world, r_c couldn't give a rats tail what the new leader did with the life for [virtue]."`
**Rats** should be rat's.

`"text": "Was thius a joke? The murk-covered form of r_c couldn't believe that m_c got chosen to be leader. r_c rolls {PRONOUN/r_c/poss} eyes and gives a life for [virtue] with an incredulous sigh."`
**Thius** should be this. It also might be worth considering changing, "r_c couldn't believe that m_c got chosen to be leader," to: "r_c couldn't believe that m_c was chosen to be leader." It flows a bit better in my opinion.

Gotta be honest, all of these are super cool! I love seeing the Dark Forest get some spice.

**Comment by Ronfaure** [comment]
> `"text": "Puffing out {PRONOUN/r_c/poss} chest, r_c gives m_c a life for [virtue] and dares {PRONOUN/m_c/object} to make c_n an even better Clan than anyone ever could!"` I'm pretty sure that after {PRONOUN/r_c/poss}, there are two spaces instead of one. You might want to go check that.
> 
> `"text": "Such a theatric attitude had no place in the Dark Forest. But the gloom-covered spirit of r_c gives m_c a life for [virtue] with silent contempt in {PRONOUN/r_c/poss} eyes regardless of {PRONOUN/r_c/poss} feelings on the matter."` Same thing as above. I could be wrong, but might be worth a quick check.
> 
> `"text": "So long as m_c uses {PRONOUN/m_c/poss} rebellious ways to destroy the hold StarClan has on the world, r_c couldn't give a rats tail what the new leader did with the life for [virtue]."` **Rats** should be rat's.
> 
> `"text": "Was thius a joke? The murk-covered form of r_c couldn't believe that m_c got chosen to be leader. r_c rolls {PRONOUN/r_c/poss} eyes and gives a life for [virtue] with an incredulous sigh."` **Thius** should be this. It also might be worth considering changing, "r_c couldn't believe that m_c got chosen to be leader," to: "r_c couldn't believe that m_c was chosen to be leader." It flows a bit better in my opinion.
> 
> Gotta be honest, all of these are super cool! I love seeing the Dark Forest get some spice.

Thank you again! Got these fixed as well :)

**Review by Ryos00 — APPROVED** [review]

**Pull request merged**
