### PR TITLE
aug10 save file converter

### PR DESCRIPTION
**Pull request by lillithrosepup**
ported from web ver !

### CODE REVIEW

**Review by Ryos00 — APPROVED** [review]

**Review by Lixxis — COMMENTED** [review]
I think we should wait for this, because of the feature freeze. 
It might have more impact than we thought, I would suggest adding this after the new update.

**Comment by lillithrosepup** [comment]
imo, this would be better to include in the update bc a bunch of people will see the new update after not playing for a while and it would help lessen the load on techsupport from all the people moving over. and even if it doesnt work somehow, i made sure it doesnt delete the old csv, so they can still use the web convertor

**Comment by Lixxis** [comment]
I see no reason, why they are going to be more ppl playing this update than any other update before. 
I'm not worried about that, the files are going to be ruined I'm more afraid, that this load would result into a buggy clan with errors. The next update is soon and in my opinion such a conversion would need more testing.

**Comment by Lixxis** [comment]
@ImLvna 
If you fix the merge conflict, we can try to merge it

**Comment by larkgz** [comment]
Some minor corrections/additions for the conversion:
- rather than `status`, `age` should be be the one set to `senior`
- if a cat has the trait `clever`, it should be converted to `wise` due to the clever trait being removed
- `eye_colour2` is typically `null` if the cat does not have heterochromia

**Comment by lillithrosepup** [comment]
closing as it seems it is already ingame?

**Pull request closed without merging**
