### PR TITLE
Always show cat's mate in mediation screen

### PR DESCRIPTION
**Pull request by lillithrosepup**

### CODE REVIEW

**Comment by keyraven** [comment]
This was not originally put in since it would often cause text to overflow when displayed both the name of a cats mate, and their relatedness to the target cat.

**Review by scribblecrumb — CHANGES_REQUESTED** [review]
Could implement the name shortening (Bubblingnoise to Bubblingn...) code, though it would look a little funky to see Bubblingn...'s mate.  Not the worst thing though.  A different idea could be a tooltip that appears when hovering over the mate text that lists the mate's name?

**Comment by lillithrosepup** [comment]
what should the limit be? 9?

**Comment by scribblecrumb** [comment]
eh, whatever looks good I guess

**Comment by keyraven** [comment]
I think the limit needs to be small enough so that the message never goes goes beyond a single line. Otherwise, you will get overflowing with the relation information. However, that might require a really small limit, like 3 or 4,

**Comment by scribblecrumb** [comment]
It might be better to show the mates name upon hovering over the mate text!

**Comment by Lixxis** [comment]
@scribblecrumb 
There were some commits, does the issues you address still exist?

**Comment by lillithrosepup** [comment]
Closing as inactive

**Pull request closed without merging**
