### PR TITLE
Dilute tints PR

### PR DESCRIPTION
**Pull request by MaggietheMink**
Hello, dilute tints are basically the opposite of normal tints, instead of adding a color to a pelt, which makes it darker, they subtract a color which makes the pelt lighter, this adds quite a bit of variation while changing very little code. The current dilute tint colors are a heavy WIP, they are just the exact colors of the normal tints but reversed, they definitely need altered (which I'm very willing to do) and they lead to some weird looking cats. I was thinking there could just be three dilute tints, a neutral one, a warm tinted one and a cool tinted one. But again I'm fine with whatever the art team thinks is best. :>

Attached are a few random examples, if i did it correctly the first image should a a cat with a dilute tint, and the second should be the same cat with no tint. I'm MaggieTheMink on discord if anyone wants to talk, I'm ok with pings and Dms!

Screenshot 2024-05-12 at 10 27 16 PM
Screenshot 2024-05-12 at 10 28 54 PM
Screenshot 2024-05-12 at 10 34 59 PM
Screenshot 2024-05-12 at 10 35 35 PM
Screenshot 2024-05-12 at 10 30 02 PM
Screenshot 2024-05-12 at 10 31 39 PM
Screenshot 2024-05-12 at 10 30 15 PM
Screenshot 2024-05-12 at 10 31 47 PM
Screenshot 2024-05-12 at 10 37 12 PM
Screenshot 2024-05-12 at 10 37 32 PM
Screenshot 2024-05-12 at 10 52 38 PM
Screenshot 2024-05-12 at 10 52 46 PM

### CODE REVIEW

**Comment by keyraven** [comment]
We have discussed adding tint w/ alternative blend modes before, but the discussion never got very far. I think this is a good implementation of that idea.  

I agree that the current WIP tints are a bit strong, but I think this is workable. However, @anjubatus typically approves of any sprite changes. What are your thoughts?

**Comment by anjubatus** [comment]
Hello! I think this is a very good idea and your examples mostly look very nice. I also agree three tints may be enough for that. As far as your examples go, the blue is coming on too strongly on the dark grey and dark brown pelts. Once you've made some adjustments, I'd love to see more examples! Would you be able to show how each tint looks on the same pelt color for example?

I also have a request related to tints, since you're already adjusting them - I think for regular tints, the blue ones shouldn't be allowed for grey cats anymore (unsure if that means they're automatically grouped with black and white cats). This is because the regular versions of the grey pelt colors already have a small blue tint in them, so adding more blue just makes the blue kind of overwhelming as I've noticed.

**Review by anjubatus — CHANGES_REQUESTED** [review]
Adjusting the dilute tints & disallowing blue normal tint for grey pelts

**Comment by MaggietheMink** [comment]
> Hello! I think this is a very good idea and your examples mostly look very nice. I also agree three tints may be enough for that. As far as your examples go, the blue is coming on too strongly on the dark grey and dark brown pelts. Once you've made some adjustments, I'd love to see more examples! Would you be able to show how each tint looks on the same pelt color for example?
> 
> I also have a request related to tints, since you're already adjusting them - I think for regular tints, the blue ones shouldn't be allowed for grey cats anymore (unsure if that means they're automatically grouped with black and white cats). This is because the regular versions of the grey pelt colors already have a small blue tint in them, so adding more blue just makes the blue kind of overwhelming as I've noticed.

Alright, I’ll adjust them later tonight! Would I be able to @ you in the sprites channel for that?

**Comment by keyraven** [comment]
Can you post some comparison images of the adjusted tint colors?

**Comment by MaggietheMink** [comment]
> Can you post some comparison images of the adjusted tint colors?

I @ed you in discord a few days ago about this but I don’t know if you checked

**Comment by Thlumyn** [comment]
Can you post images in the github here? @MaggietheMink

**Comment by MaggietheMink** [comment]
new tints on all colors and dark brown as close up examples

Screenshot_2024-05-19_at_1 08 21_PM
Screenshot_2024-05-19_at_1 08 30_PM
Screenshot_2024-05-19_at_1 08 38_PM
Screenshot_2024-05-19_at_1 08 47_PM
Screenshot_2024-05-19_at_1 09 06_PM
Screenshot_2024-05-19_at_1 09 28_PM
Screenshot_2024-05-19_at_1 09 37_PM
Screenshot_2024-05-19_at_1 09 19_PM

**Review by anjubatus — APPROVED** [review]

**Pull request merged**
