### PR TITLE
Fixed Issue #1867

### LINKED ISSUE #1867: Strange behavior if Clan is named "Current"
**Type:** code
**Summary:** if the "current clan" is named "currentclan", the game does not load it upon closing and reopening, even though "current" is listed in currentclan.txt. instead it seems to load whatever save is first in alphabetical order
**Grade:** regular
**Occurrence:** frequent
**Reproduce:** name a clan "currentclan" with at least one other clan that comes before it in alphabetical order. the clan the game opened instead for me was biteclan, for instance
**Commit:** 3645edf2b3a2c49c7a879f22410fb1ea854a7cd0

### PR DESCRIPTION
**Pull request by PoppyBlossom**
## About The Pull Request

This pull request fixes the issue "Strange behavior if Clan is named "Current" #1867", this PR only changes one line of the code. This works by checking to make sure the clan name isn't current before deleting the txt format of the file so the currentclan.txt wouldn't get mistakenly deleted.

## Linked Issues
Fixes: #1867

## Proof of Testing
The bug no longer occurs by following the steps given by the issue, and the game is still functioning.

## Changelog/Credits
Minor bug fix?

### CODE REVIEW

**Comment by ZtheCorgi** [comment]
tysm for looking into this bug! it was driving me crazy for a while there

**Comment by PoppyBlossom** [comment]
You're welcome :3

**Review by scribblecrumb — APPROVED** [review]

**Comment by scribblecrumb** [comment]
Thanks for the fix!  Do you have the dev role already on our discord?  I don't recognize your name ^^;  If not, it's available to you if you want it (it will give you access to the dev side of the server), just let me know!

**Comment by PoppyBlossom** [comment]
@scribblecrumb  I personally don't use Discord, but I will try to get one if it's required. And I would love to know more about the roles on Discord.

**Comment by scribblecrumb** [comment]
@PoppyBlossom Not required at all!  You're welcome to continue making contributions as you have been.  However, we do the majority of our discussing and planning via the discord, so if you were interested in contributing towards larger features then it would be a good way to get involved in the deeper aspects of the project.  

Since you've already had contributions merged, you'd be given the Code Developer role.  You'd have the ability to see and post on the developer side of the discord.  There are also writing, art, and audio developers; as well as senior developers, who also act as the repository maintainers (I'm one of the seniors) and handle the approval of pull requests.

**Comment by PoppyBlossom** [comment]
@scribblecrumb Thank you for telling me all of this! I am excited to look into it and maybe join the Discord server. However, I don't really think I'm that good of a developer _(at least not yet)_, so it may or may not happen.

**Pull request merged**
