### PR TITLE
[ENHANCEMENT] Change transing function to use ShortEvents

### PR DESCRIPTION
**Pull request by bakermor**
## About The Pull Request
Transferred hardcoded transing functionality from events.py to 2 misc ShortEvents with "transition" subtype. Adds 2 new attributes to ShortEvents: gender for m_c, and new_gender. 

Coming out is still rolled for each cat every moon. Chances for transitioning are based on age and are the same as before just moved to game_config.

Event text is the same as before but uses m_c's new pronouns.

## Why This Is Good For ClanGen
It is more consistent to handle these events as ShortEvents and provides the opportunity to add more variations of the event.

## Linked Issues
#2424

## Proof of Testing
mtf:
image
image

ftm:
image
image

mtnb/ftnb:
image
image
image

### CODE REVIEW

**Comment by Vickarooni** [comment]
i'm not a dev or anything, but i want to put my own two cents. putting trans chances in game_config might make it more accessible to transphobes since they could just... set the chances to 0. and i'm positive that's not something we _want_,,,

**Comment by scribblecrumb** [comment]
> i'm not a dev or anything, but i want to put my own two cents. putting trans chances in game_config might make it more accessible to transphobes since they could just... set the chances to 0. and i'm positive that's not something we _want_,,,

I'll bring it up to the other senior devs.  However, I will say that it's hardly difficult to just go into the source code and do that anyways without it being in game_config.  Our stance has always been plainly about in-game toggles so I'm not sure how that stance will transfer to game_config settings.  We'll discuss it.

**Comment by ZtheCorgi** [comment]
hopefully transphobes will be upset enough that we added pronouns to stay away regardless /hj

**Comment by Vickarooni** [comment]
> I'll bring it up to the other senior devs. However, I will say that it's hardly difficult to just go into the source code and do that anyways without it being in game_config. Our stance has always been plainly about in-game toggles so I'm not sure how that stance will transfer to game_config settings. We'll discuss it.

that's true, but compared to source code, game_config is WAY more easily accessible, it's in the resources folder and is even available in a stable download .. and transphobes are just kind of Like That, i wouldn't be surprised if they would be willing to go through that tiny bit of extra effort just to disable a feature they don't like that wasn't as easily modifiable before.

**Comment by scribblecrumb** [comment]
> > I'll bring it up to the other senior devs. However, I will say that it's hardly difficult to just go into the source code and do that anyways without it being in game_config. Our stance has always been plainly about in-game toggles so I'm not sure how that stance will transfer to game_config settings. We'll discuss it.
> 
> that's true, but compared to source code, game_config is WAY more easily accessible, it's in the resources folder and is even available in a stable download .. and transphobes are just kind of Like That, i wouldn't be surprised if they would be willing to go through that tiny bit of extra effort just to disable a feature they don't like that wasn't as easily modifiable before.

Senior devs have discussed and decided that we're just gonna add a catch that prevents transing chance from ever being zero (unless someone actively undoes the code we add).  That way it can be in game_config for those who want to modify the chance in good faith.

**Comment by Vickarooni** [comment]
> Senior devs have discussed and decided that we're just gonna add a catch that prevents transing chance from ever being zero (unless someone actively undoes the code we add). That way it can be in game_config for those who want to modify the chance in good faith.

that's awesome! thank you so much for hearing me out ^^ tbh that was actually an idea that i had but didn't know how to bring it up nor would i know how to code it in (and if it was even plausible, for that matter) so i'm glad it crossed y'alls minds too. appreciate it, y'all r the best :)

**Review by scribblecrumb — APPROVED** [review]

**Pull request merged**
