### PR TITLE
fixes for clan-specific settings typos and patrol typos

### PR DESCRIPTION
**Pull request by selkirks**
fixed typos in the clan specific settings page and patrols, including two halloween specific patrols

typos reported here:
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-1783286224
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-1783306328
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-1783656637
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-1783900184
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-1806662057

### CODE REVIEW

**Comment by keyraven** [comment]
Great Fixes! Since these fixes apply to the current release version, it would be best to merge these into the `release-0.10` branch. However, since your branch includes commits from the current dev version, so I can't change the target branch. Could you cherry-pick your two commits into a copy of `release-0.10`, and recreate this pull request?

**Comment by selkirks** [comment]
> Great Fixes! Since these fixes apply to the current release version, it would be best to merge these into the `release-0.10` branch. However, since your branch includes commits from the current dev version, so I can't change the target branch. Could you cherry-pick your two commits into a copy of `release-0.10`, and recreate this pull request?

yaya ofc! ill do it when i get home from school!

**Comment by selkirks** [comment]
> Great Fixes! Since these fixes apply to the current release version, it would be best to merge these into the `release-0.10` branch. However, since your branch includes commits from the current dev version, so I can't change the target branch. Could you cherry-pick your two commits into a copy of `release-0.10`, and recreate this pull request?

attempted to try and commit to release 1.10 on github desktop but it give me this error. logged back in and out various times, but to no avail
image

**Comment by keyraven** [comment]
@selkirks On your fork, you'll will need to create a copy of the `release-0.10` branch, then cherry-pick your commits onto the new branch. On GitHub Desktop, the easiest way to do this is to first checkout the `upstream/release-0.10` branch, then click the "new branch" button. There should be an option for the new branch to be a copy of the currently checked-out branch. You are getting that error because you don't have permission to commit directly to the ClanGen repository, which is expected. 

I would be happy to help you out over discord, if you need any additional help! My username is the same on discord: `keyraven`.

**Comment by keyraven** [comment]
We want to get a release patch out, and these fixes are good, so I cherry-picked the commits for you, and created the PR in https://github.com/ClanGenOfficial/clangen/pull/1890.  You're still the author of the commits!

**Comment by selkirks** [comment]
> We want to get a release patch out, and these fixes are good, so I cherry-picked the commits for you, and created the PR in #1890. You're still the author of the commits!

thank you! very sorry i wasnt able to commit them myself, was at school ^^” thanks so much though!!! /gen

**Comment by keyraven** [comment]
for release, here: https://github.com/ClanGenOfficial/clangen/pull/1898

**Pull request closed without merging**
