### PR TITLE
Fix debug mode from crashing on certain commands, PEP 8-ify

### PR DESCRIPTION
**Pull request by tailhaver**
- Fixes debug menu crashing when:
  - clearing the console
  - toggling / getting settings that don't exist
  - changing the FPS cap
- Makes negative numbers disable the FPS cap
- Makes debug files (debugCommands/*, debugMenu) follow the PEP 8 file naming convention

### CODE REVIEW

**Comment by archanyhm** [comment]
I'll have a look at that tomorrow. Thanks for the re-submission!

**Comment by Thlumyn** [comment]
@archanyhm @howlagon  Is this PR still active?

**Comment by tailhaver** [comment]
it might be outdated, but I have no way of updating it as I am out of the country until next month. If it fixes the bugs with the debug mode in its current state, then it is active. Otherwise it can be closed.

**Comment by tailhaver** [comment]
It would appear that this is still needed (these issues still appear on my fork of the latest commit)

**Review by Thlumyn — APPROVED** [review]

**Pull request merged**
