### PR TITLE
Ci Matrix Rewrite

### PR DESCRIPTION
**Pull request by lillithrosepup**
Commit history and actions logs are [here](https://github.com/ImLvna/clangen/actions)

Rewrites the big buildscript to a matrix
Additionally speeds up buildtime by building the self updater seperate

### CODE REVIEW

**Comment by lillithrosepup** [comment]
Requesting review from @archanyhm and maybe @Dpeta

**Comment by lillithrosepup** [comment]
oh yeah also fixes the commit history popup because apparently gh actions only gets the one commit by default

**Comment by keyraven** [comment]
@archanyhm  Can you take a quick look at this? I'm not familiar enough to properly review.

**Comment by Thlumyn** [comment]
I'm closing old PRs

**Pull request closed without merging**
