### PR TITLE
Forest of curiosities

### PR DESCRIPTION
**Pull request by Eragona**
I just wanted to update this mod to the newer dev version. I haven't added anything new yet

miniaturka moda 1

### CODE REVIEW

**Comment by Eragona** [comment]
And I will fix the conflicts manually later

**Comment by Chinch-Bug** [comment]
uh, buddy, you're trying to merge your mod _into_ clangen instead of the other way around /lh

**Comment by Eragona** [comment]
Oh...I'm so sorry, you can close this. I'll try again, this time properly (this is the fourth time, I finally have to get myself together)

**Comment by Thlumyn** [comment]
@Eragona I am going to be blocking you from the ClanGen repository, so that you don't have to worry about this happening again when you try to update your fork. Good luck with your mod; if you are interested in contributing to ClanGen itself, let me (Sable) know in the discord and I can unblock you. Thanks.

**Pull request closed without merging**
