### PR TITLE
Changed newborn kitten sprite markings

### PR DESCRIPTION
**Pull request by seyriix**
Changes the colours and patterns of the newborn kitten sprites to match the other sprites (it was bugging me :P)

**Examples** _(Before / After)_:
before / after _(Black Sokoke)_
before (2) / after (2) _(Sienna Rosette)_
before (3) / after (3) _(Chocolate Speckled)_
before (4) / after (4) _(Lilac Ticked)_

### CODE REVIEW

**Review by keyraven — CHANGES_REQUESTED** [review]
I think having unique colors colors for each newborn sprite is a good change. However, after discussion with other folk, there is still a preference for the newborn sprite to be lighter/desaturated than the rest of the life-stages.  If you are willing to revise these changes by slightly lightening or desaturating each newborn sprite, then I will happily accept these changes.

**Comment by seyriix** [comment]
> I think having unique colors colors for each newborn sprite is a good change. However, after discussion with other folk, there is still a preference for the newborn sprite to be lighter/desaturated than the rest of the life-stages. If you are willing to revise these changes by slightly lightening or desaturating each newborn sprite, then I will happily accept these changes.

Sure, I can do that! Out of curiosity, is it for aesthetics or another reason? :O

**Comment by keyraven** [comment]
> > I think having unique colors colors for each newborn sprite is a good change. However, after discussion with other folk, there is still a preference for the newborn sprite to be lighter/desaturated than the rest of the life-stages. If you are willing to revise these changes by slightly lightening or desaturating each newborn sprite, then I will happily accept these changes.
> 
> Sure, I can do that! Out of curiosity, is it for aesthetics or another reason? :O

Awesome! The paler newborn sprites are mostly for aesthetics, alongside of bit of realism. Kits are typically born slightly lighter, and darken as they age.

**Comment by seyriix** [comment]
> Awesome! The paler newborn sprites are mostly for aesthetics, alongside of bit of realism. Kits are typically born slightly lighter, and darken as they age.

That makes sense!


I've lowered the contrast between the base colour and the marking colour of each kit, which hopefully gives them the appearance of being lighter but still recognisable as the designated colour; I can of course make them lighter still but just thought I'd see how this was first :D

**Sprites v1 (old) / Sprites v2 (new) / Original:**
white v1/white v2/white og _(White Bengal)_
light brown v1/light brown v2/light brown og _(Light Brown Ticked)_
ginger v1/ginger v2/ginger og _(Ginger Rosette)_

**Comment by anjubatus** [comment]
Hello! Thank you for making the renewed pelts for newborns. Looking at your recent examples, I would push them even further with the lightening. Here's a quick example i did with the lightbrown, showing your original v1 version and my suggestion:
newborn example

**Comment by seyriix** [comment]
Sorry for the late update! 
I've lightened the colours to match the current game sprites since that seemed easiest, hopefully that's alright :D

**Original / Sprites v3 (New) / Sprites v1 (Old):**
dev 3 / v3 3 / v1 3 _(Chocolate Smoke)_
dev 2 / v3 2 / v1 2 _(Sienna Rosette)_
dev 1 / v3 1 / v1 1 _(Grey Agouti)_

**Review by keyraven — APPROVED** [review]

**Comment by seyriix** [comment]
cat-kiss

**Pull request merged**
