### PR TITLE
[BUGFIX] make icon on Clan creation screen change with dark mode setting 

### LINKED ISSUE #3141: [BUG] Clan symbol select screen should use dark mode sprites
### Type of bug

UI - anything to do with the user interface - maybe a button is not working, or the way some assets are formatted seems to be off.

### Description

See screenshots. This screen should use the lighter sprites for dark mode when in dark mode for the preview display.

### Grade

Regular - A typical bug that should be seen to soon, but doesn't necessarily break the game or inhibit the player

### Steps to reproduce the behavior

1. Proceed through clan creation process whilst in dark mode
2. The sprite has poor contrast with the background image.

### Patrol ID + Outcome Print (if applicable)

_No response_

### Commit # or Game Version Number

0.12

### Additional context

_No response_

### Screenshots

image

### PR DESCRIPTION
**Pull request by rustykitty**
## About The Pull Request
I just added a simple check when displaying Clan icons on the Clan creation screen to make the color change with dark mode.

## Why This Is Good For ClanGen
N/A

## Linked Issues
Resolves #3141

## Proof of Testing

Screenshot 2024-12-09 at 7 43 04 AM

### CODE REVIEW

**Comment by rustykitty** [comment]
BTW, those force pushes above are me rebasing my branch from development to release_0.12.0 and then dropping the extra commits.

**Comment by scribblecrumb** [comment]
Oops, this is the opposite of the request!  The sprite close up:
image
is what we'd like to have as the light color.  The sprites within the selection box should stay the original color.

**Comment by rustykitty** [comment]
Oops..

**Comment by rustykitty** [comment]
I believe this was what was intended of the PR? 
image

**Comment by scribblecrumb** [comment]
Yes, that's correct!  I just tested it and it seems like the color of the example sprite doesn't change to the light version until you select a different sprite.  

https://github.com/user-attachments/assets/fd1446b8-76bf-4828-a4f9-deada6030f71

**Comment by rustykitty** [comment]
Screenshot 2024-12-13 at 6 38 34 AM

**Review by scribblecrumb — APPROVED** [review]

**Pull request merged**
