### PR TITLE
JSON Schema for Shortevents

### PR DESCRIPTION
**Pull request by larkgz**
## About The Pull Request

* Adds a JSON schema for shortevents
* Adds tests that run in the ci and script that can be run locally to check that shortevents align with schema (NOTE: currently fails due to some incorrect formatting in shortevent JSON files)
* Associates shortevents with schema in Visual Studio Code

## Linked Issues

#1864

### CODE REVIEW

**Comment by j-gynn** [comment]
I know you created the test, but we'd like it to pass before we add it to the repository. Could you make the necessary changes? Thank you!

**Comment by larkgz** [comment]
The changes are in #3190. When the release bugfixes are pulled back into dev I can merge.

**Comment by larkgz** [comment]
@j-gynn Tests pass now!

**Review by j-gynn — APPROVED** [review]
LGTM

**Pull request merged**
